'learning_rate': 0.03
'momentum': 0.9
'weight_decay' : 0.0
'amp_level': "O2"
'use_amp': True
'gpus': -1
'once_cycle_policy': False
#     'batch_size': 224,
'batch_size': 40
'min_epochs': 200
'max_epochs': 300
'transform_resize': 224
#'model_name': "resnet18"
'model_name': "wide_resnet50_2"
#     'model_name': "custom",
'pretrained': True
'optimizer_name': 'SGD' # not used atm
#'data_dir': "utdmhad/UTDMHAD_skeletonapproach_id011_gradient_alpha_size_1_attention_filter_0.2"
'data_dir': "utdmhad/UTDMHAD_skeletonapproach_id011_gradient_alpha_size_1_no_attention_filter_0.2"
'save_path': "logs"
#     'model_dir': f"{data_dir}/models_lightning/",
'model_dir': "models/iros_final1/224_transform1/b2/normalized_true"
